# Generated by Django 3.2 on 2022-02-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KewWordsMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=100)),
                ('last_search_by', models.CharField(max_length=100)),
                ('last_search_date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('result_showed', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('search_date', models.DateField()),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KewWords_tb', to='keywords.kewwordsmd')),
            ],
        ),
    ]
